### ISSUE TITLE
Alternative UI

### ISSUE THREAD

**Issue by jcuenod** [parabible/parabible-client#23]
Office-ui-fabric is heavy (contributing well over half the weight of `bundle.js` thanks to stuff like lodash etc.). It would be great if we could lighten it up somehow.

- Maybe we need to just optimise stuff we're already doing
- Maybe can consider an alternative framework:
  - https://rsuitejs.com/en/components/overview seems to cover the bases and looks great. It's chinese though, so who knows about support...
  - https://atlaskit.atlassian.com/ looks cool and has some nice backing. Not sure about their general page structure ideals though. Might need to rethink

Bear in mind:
- Are we trying to support mobile? (there are regular mobile users!)
- Are we trying to support IE? (edge?)

**Comment by jcuenod** [comment]
Well I just tested **rsuite** and it took 2mb to build a page with their css and a button component. Probably not worth it.

**Atlaskit** on the other hand gave me something similar in 200k. The problem is that they don't have a horizontal menu header type thing.

I'll close this for now and keep thinking about it...

**Comment by jcuenod** [comment]
Had another go with **rsuite**. Turns out that the whole package is being included (so that's a bit better) but it's still substantially larger than `office-ui-fabric`'s 600k.
They do have some great components though...

**Comment by simonguo** [comment]
@jcuenod   I am very happy that you try `rsuite`, I can help if you need it.
